#  ___        _  ___           __ _
# | _ \___ __| |/ __|_ _ __ _ / _| |_   ___ _ _ __ _
# |   / -_) _` | (__| '_/ _` |  _|  _|_/ _ \ '_/ _` |
# |_|_\___\__,_|\___|_| \__,_|_|  \__(_)___/_| \__, |
#                                              |___/
#

reboot-message: "%player% asked for a reboot in %minutes% minutes for the following reason: %reason%"
reboot-message-s: "%player% asked for a reboot in %seconds% seconds for the following reason: %reason%"
console-scheduled-minutes: 15

kick-message: "The server is restarting"
default-reason: "None"
minute-countdown: "The server is restarting in %minutes% minutes"
second-countdown: "The server is restarting in %seconds% seconds"

cancel-message: "Server reboot has been canceled"
console-message: "The daily reboot has been scheduled in %minutes% minutes"