#  ___        _  ___           __ _
# | _ \___ __| |/ __|_ _ __ _ / _| |_   ___ _ _ __ _
# |   / -_) _` | (__| '_/ _` |  _|  _|_/ _ \ '_/ _` |
# |_|_\___\__,_|\___|_| \__,_|_|  \__(_)___/_| \__, |
#                                              |___/
#

reboot-minute-message: "%player% asked for a reboot in %minutes% minutes for the following reason: %reason%"
reboot-second-message: "%player% asked for a reboot in %seconds% seconds for the following reason: %reason%"

maxCooldown-minutes: 15

reboot-kick-message: "The server is restarting"
reboot-default-message: "None"

countdown-minute-message: "The server is restarting in %minutes% minutes"
countdown-second-message: "The server is restarting in %seconds% seconds"

reboot-cancel-message: "Server reboot has been canceled"
reboot-console-message: "The daily reboot has been scheduled in %minutes% minutes"